project:
  type: book

book:
  title: "Programação Matemática"
  author: "Andreza C. Beezão Moreira e Mayron César O. Moreira"
  date: "2025-09-17"

  chapters:
    - index.qmd
    #- 01-introducao.qmd
    #- 02-modelagem.qmd
    - 03-simplex.qmd
    #- 04-dualidade.qmd
    - 05-otimizacao-discreta.qmd
    #- 06-fluxo-redes.qmd
    #- 07-avaliacao.qmd
    #- 08-exercicios.qmd

bibliography: referencias.bib

format:
  html:
    theme: cosmo
    
execute:
  kernel: or_env

